use "$created_data\individs_by_duration_wide.dta", clear

egen nmis_age = rmiss(age_focal*)
tab nmis_age, m

drop if nmis_age==17 // for now, just so this is actually complete
drop if birth_yr_all==. // for now, just so this is actually complete
drop if raceth_fixed_focal==. // for now, just so this is actually complete

mi set wide
mi register imputed weekly_hrs_t_focal* housework_focal* employed_focal_rec* earnings_t_focal* educ_focal* college_focal* children* NUM_CHILDREN_* AGE_YOUNG_CHILD_* relationship_* partnered* TOTAL_INCOME_T_FAMILY*
mi register regular FIRST_BIRTH_YR birth_yr_all rel_start_all SEX raceth_fixed_focal sample_type

mi misstable nested weekly_hrs_t_focal* employed_focal_rec* // so, these aren't nested. is this because I need to go back and fill in the variables of employed that I based on whether or not they have earnings / hours?
// https://www.statalist.org/forums/forum/general-stata-discussion/general/1605083-multiple-imputation-and-conditional

browse weekly_hrs_t_focal5 employed_focal5
tab weekly_hrs_t_focal5 employed_focal5, m

// start imputation
#delimit ;

mi impute chained

/* Employment hours */
(pmm, knn(5) include (                weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16 housework_focal0 i.employed_focal_rec0 earnings_t_focal0 i.educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 i.partnered0 TOTAL_INCOME_T_FAMILY0) conditional(if employed_focal_rec0==1)) weekly_hrs_t_focal0
(pmm, knn(5) include (               weekly_hrs_t_focal0 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16  housework_focal1 i.employed_focal_rec1 earnings_t_focal1 i.educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 i.partnered1 TOTAL_INCOME_T_FAMILY1) conditional(if employed_focal_rec1==1)) weekly_hrs_t_focal1
(pmm, knn(5) include (              weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16   housework_focal2 i.employed_focal_rec2 earnings_t_focal2 i.educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 i.partnered2 TOTAL_INCOME_T_FAMILY2) conditional(if employed_focal_rec2==1)) weekly_hrs_t_focal2
(pmm, knn(5) include (             weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16    housework_focal3 i.employed_focal_rec3 earnings_t_focal3 i.educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 i.partnered3 TOTAL_INCOME_T_FAMILY3) conditional(if employed_focal_rec3==1)) weekly_hrs_t_focal3
(pmm, knn(5) include (            weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16     housework_focal4 i.employed_focal_rec4 earnings_t_focal4 i.educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 i.partnered4 TOTAL_INCOME_T_FAMILY4) conditional(if employed_focal_rec4==1)) weekly_hrs_t_focal4
(pmm, knn(5) include (           weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16      housework_focal5 i.employed_focal_rec5 earnings_t_focal5 i.educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 i.partnered5 TOTAL_INCOME_T_FAMILY5) conditional(if employed_focal_rec5==1)) weekly_hrs_t_focal5
(pmm, knn(5) include (          weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16       housework_focal6 i.employed_focal_rec6 earnings_t_focal6 i.educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 i.partnered6 TOTAL_INCOME_T_FAMILY6) conditional(if employed_focal_rec6==1)) weekly_hrs_t_focal6
(pmm, knn(5) include (         weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16        housework_focal7 i.employed_focal_rec7 earnings_t_focal7 i.educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 i.partnered7 TOTAL_INCOME_T_FAMILY7) conditional(if employed_focal_rec7==1)) weekly_hrs_t_focal7
(pmm, knn(5) include (        weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16         housework_focal8 i.employed_focal_rec8 earnings_t_focal8 i.educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 i.partnered8 TOTAL_INCOME_T_FAMILY8) conditional(if employed_focal_rec8==1)) weekly_hrs_t_focal8
(pmm, knn(5) include (       weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16          housework_focal9 i.employed_focal_rec9 earnings_t_focal9 i.educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 i.partnered9 TOTAL_INCOME_T_FAMILY9) conditional(if employed_focal_rec9==1)) weekly_hrs_t_focal9
(pmm, knn(5) include (      weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16           housework_focal10 i.employed_focal_rec10 earnings_t_focal10 i.educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 i.partnered10 TOTAL_INCOME_T_FAMILY10) conditional(if employed_focal_rec10==1)) weekly_hrs_t_focal10
(pmm, knn(5) include (     weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16            housework_focal11 i.employed_focal_rec11 earnings_t_focal11 i.educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 i.partnered11 TOTAL_INCOME_T_FAMILY11) conditional(if employed_focal_rec11==1)) weekly_hrs_t_focal11
(pmm, knn(5) include (    weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16             housework_focal12 i.employed_focal_rec12 earnings_t_focal12 i.educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 i.partnered12 TOTAL_INCOME_T_FAMILY12) conditional(if employed_focal_rec12==1)) weekly_hrs_t_focal12
(pmm, knn(5) include (   weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16              housework_focal13 i.employed_focal_rec13 earnings_t_focal13 i.educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 i.partnered13 TOTAL_INCOME_T_FAMILY13) conditional(if employed_focal_rec13==1)) weekly_hrs_t_focal13
(pmm, knn(5) include (  weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal15 weekly_hrs_t_focal16               housework_focal14 i.employed_focal_rec14 earnings_t_focal14 i.educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 i.partnered14 TOTAL_INCOME_T_FAMILY14) conditional(if employed_focal_rec14==1)) weekly_hrs_t_focal14
(pmm, knn(5) include ( weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal16                housework_focal15 i.employed_focal_rec15 earnings_t_focal15 i.educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 i.partnered15 TOTAL_INCOME_T_FAMILY15) conditional(if employed_focal_rec15==1)) weekly_hrs_t_focal15
(pmm, knn(5) include (weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15                 housework_focal16 i.employed_focal_rec16 earnings_t_focal16 i.educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 i.partnered16 TOTAL_INCOME_T_FAMILY16) conditional(if employed_focal_rec16==1)) weekly_hrs_t_focal16


/* Housework Hours */
(pmm, knn(5) include (                housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16 weekly_hrs_t_focal0 i.employed_focal_rec0 earnings_t_focal0 i.educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 i.partnered0 TOTAL_INCOME_T_FAMILY0)) housework_focal0
(pmm, knn(5) include (               housework_focal0 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16  weekly_hrs_t_focal1 i.employed_focal_rec1 earnings_t_focal1 i.educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 i.partnered1 TOTAL_INCOME_T_FAMILY1)) housework_focal1
(pmm, knn(5) include (              housework_focal0 housework_focal1 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16   weekly_hrs_t_focal2 i.employed_focal_rec2 earnings_t_focal2 i.educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 i.partnered2 TOTAL_INCOME_T_FAMILY2)) housework_focal2
(pmm, knn(5) include (             housework_focal0 housework_focal1 housework_focal2 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16    weekly_hrs_t_focal3 i.employed_focal_rec3 earnings_t_focal3 i.educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 i.partnered3 TOTAL_INCOME_T_FAMILY3)) housework_focal3
(pmm, knn(5) include (            housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16     weekly_hrs_t_focal4 i.employed_focal_rec4 earnings_t_focal4 i.educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 i.partnered4 TOTAL_INCOME_T_FAMILY4)) housework_focal4
(pmm, knn(5) include (           housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16      weekly_hrs_t_focal5 i.employed_focal_rec5 earnings_t_focal5 i.educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 i.partnered5 TOTAL_INCOME_T_FAMILY5)) housework_focal5
(pmm, knn(5) include (          housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16       weekly_hrs_t_focal6 i.employed_focal_rec6 earnings_t_focal6 i.educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 i.partnered6 TOTAL_INCOME_T_FAMILY6)) housework_focal6
(pmm, knn(5) include (         housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16        weekly_hrs_t_focal7 i.employed_focal_rec7 earnings_t_focal7 i.educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 i.partnered7 TOTAL_INCOME_T_FAMILY7)) housework_focal7
(pmm, knn(5) include (        housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16         weekly_hrs_t_focal8 i.employed_focal_rec8 earnings_t_focal8 i.educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 i.partnered8 TOTAL_INCOME_T_FAMILY8)) housework_focal8
(pmm, knn(5) include (       housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16          weekly_hrs_t_focal9 i.employed_focal_rec9 earnings_t_focal9 i.educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 i.partnered9 TOTAL_INCOME_T_FAMILY9)) housework_focal9
(pmm, knn(5) include (      housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16           weekly_hrs_t_focal10 i.employed_focal_rec10 earnings_t_focal10 i.educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 i.partnered10 TOTAL_INCOME_T_FAMILY10)) housework_focal10
(pmm, knn(5) include (     housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16            weekly_hrs_t_focal11 i.employed_focal_rec11 earnings_t_focal11 i.educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 i.partnered11 TOTAL_INCOME_T_FAMILY11)) housework_focal11
(pmm, knn(5) include (    housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal13 housework_focal14 housework_focal15 housework_focal16             weekly_hrs_t_focal12 i.employed_focal_rec12 earnings_t_focal12 i.educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 i.partnered12 TOTAL_INCOME_T_FAMILY12)) housework_focal12
(pmm, knn(5) include (   housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal14 housework_focal15 housework_focal16              weekly_hrs_t_focal13 i.employed_focal_rec13 earnings_t_focal13 i.educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 i.partnered13 TOTAL_INCOME_T_FAMILY13)) housework_focal13
(pmm, knn(5) include (  housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal15 housework_focal16               weekly_hrs_t_focal14 i.employed_focal_rec14 earnings_t_focal14 i.educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 i.partnered14 TOTAL_INCOME_T_FAMILY14)) housework_focal14
(pmm, knn(5) include ( housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal16                weekly_hrs_t_focal15 i.employed_focal_rec15 earnings_t_focal15 i.educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 i.partnered15 TOTAL_INCOME_T_FAMILY15)) housework_focal15
(pmm, knn(5) include (housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15                 weekly_hrs_t_focal16 i.employed_focal_rec16 earnings_t_focal16 i.educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 i.partnered16 TOTAL_INCOME_T_FAMILY16)) housework_focal16


/* Employment Status */
(logit, include (                i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16  housework_focal0  i.educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 i.partnered0 TOTAL_INCOME_T_FAMILY0)) employed_focal_rec0
(logit, include (               i.employed_focal_rec0 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16  weekly_hrs_t_focal0 housework_focal1 earnings_t_focal0 i.educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 i.partnered1 TOTAL_INCOME_T_FAMILY1)) employed_focal_rec1
(logit, include (              i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16   weekly_hrs_t_focal1 housework_focal2 earnings_t_focal1 i.educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 i.partnered2 TOTAL_INCOME_T_FAMILY2)) employed_focal_rec2
(logit, include (             i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16    weekly_hrs_t_focal2 housework_focal3 earnings_t_focal2 i.educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 i.partnered3 TOTAL_INCOME_T_FAMILY3)) employed_focal_rec3
(logit, include (            i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16     weekly_hrs_t_focal3 housework_focal4 earnings_t_focal3 i.educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 i.partnered4 TOTAL_INCOME_T_FAMILY4)) employed_focal_rec4
(logit, include (           i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16      weekly_hrs_t_focal4 housework_focal5 earnings_t_focal4 i.educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 i.partnered5 TOTAL_INCOME_T_FAMILY5)) employed_focal_rec5
(logit, include (          i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16       weekly_hrs_t_focal5 housework_focal6 earnings_t_focal5 i.educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 i.partnered6 TOTAL_INCOME_T_FAMILY6)) employed_focal_rec6
(logit, include (         i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16        weekly_hrs_t_focal6 housework_focal7 earnings_t_focal6 i.educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 i.partnered7 TOTAL_INCOME_T_FAMILY7)) employed_focal_rec7
(logit, include (        i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16         weekly_hrs_t_focal7 housework_focal8 earnings_t_focal7 i.educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 i.partnered8 TOTAL_INCOME_T_FAMILY8)) employed_focal_rec8
(logit, include (       i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16          weekly_hrs_t_focal8 housework_focal9 earnings_t_focal8 i.educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 i.partnered9 TOTAL_INCOME_T_FAMILY9)) employed_focal_rec9
(logit, include (      i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16           weekly_hrs_t_focal9 housework_focal10 earnings_t_focal9 i.educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 i.partnered10 TOTAL_INCOME_T_FAMILY10)) employed_focal_rec10
(logit, include (     i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16            weekly_hrs_t_focal10 housework_focal11 earnings_t_focal10 i.educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 i.partnered11 TOTAL_INCOME_T_FAMILY11)) employed_focal_rec11
(logit, include (    i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16             weekly_hrs_t_focal11 housework_focal12 earnings_t_focal11 i.educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 i.partnered12 TOTAL_INCOME_T_FAMILY12)) employed_focal_rec12
(logit, include (   i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec14 i.employed_focal_rec15 i.employed_focal_rec16              weekly_hrs_t_focal12 housework_focal13 earnings_t_focal12 i.educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 i.partnered13 TOTAL_INCOME_T_FAMILY13)) employed_focal_rec13
(logit, include (  i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec15 i.employed_focal_rec16               weekly_hrs_t_focal13 housework_focal14 earnings_t_focal13 i.educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 i.partnered14 TOTAL_INCOME_T_FAMILY14)) employed_focal_rec14
(logit, include ( i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec16                weekly_hrs_t_focal14 housework_focal15 earnings_t_focal14 i.educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 i.partnered15 TOTAL_INCOME_T_FAMILY15)) employed_focal_rec15
(logit, include (i.employed_focal_rec0 i.employed_focal_rec1 i.employed_focal_rec2 i.employed_focal_rec3 i.employed_focal_rec4 i.employed_focal_rec5 i.employed_focal_rec6 i.employed_focal_rec7 i.employed_focal_rec8 i.employed_focal_rec9 i.employed_focal_rec10 i.employed_focal_rec11 i.employed_focal_rec12 i.employed_focal_rec13 i.employed_focal_rec14 i.employed_focal_rec15                 weekly_hrs_t_focal15 housework_focal16 earnings_t_focal15 i.educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 i.partnered16 TOTAL_INCOME_T_FAMILY16)) employed_focal_rec16

/* Annual Earnings */
(pmm, knn(5) include (                earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16 weekly_hrs_t_focal0 i.employed_focal_rec0 housework_focal0 i.educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 i.partnered0 TOTAL_INCOME_T_FAMILY0)) earnings_t_focal0
(pmm, knn(5) include (               earnings_t_focal0 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16  weekly_hrs_t_focal1 i.employed_focal_rec1 housework_focal1 i.educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 i.partnered1 TOTAL_INCOME_T_FAMILY1)) earnings_t_focal1
(pmm, knn(5) include (              earnings_t_focal0 earnings_t_focal1 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16   weekly_hrs_t_focal2 i.employed_focal_rec2 housework_focal2 i.educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 i.partnered2 TOTAL_INCOME_T_FAMILY2)) earnings_t_focal2
(pmm, knn(5) include (             earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16    weekly_hrs_t_focal3 i.employed_focal_rec3 housework_focal3 i.educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 i.partnered3 TOTAL_INCOME_T_FAMILY3)) earnings_t_focal3
(pmm, knn(5) include (            earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16     weekly_hrs_t_focal4 i.employed_focal_rec4 housework_focal4 i.educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 i.partnered4 TOTAL_INCOME_T_FAMILY4)) earnings_t_focal4
(pmm, knn(5) include (           earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16      weekly_hrs_t_focal5 i.employed_focal_rec5 housework_focal5 i.educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 i.partnered5 TOTAL_INCOME_T_FAMILY5)) earnings_t_focal5
(pmm, knn(5) include (          earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16       weekly_hrs_t_focal6 i.employed_focal_rec6 housework_focal6 i.educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 i.partnered6 TOTAL_INCOME_T_FAMILY6)) earnings_t_focal6
(pmm, knn(5) include (         earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16        weekly_hrs_t_focal7 i.employed_focal_rec7 housework_focal7 i.educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 i.partnered7 TOTAL_INCOME_T_FAMILY7)) earnings_t_focal7
(pmm, knn(5) include (        earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16         weekly_hrs_t_focal8 i.employed_focal_rec8 housework_focal8 i.educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 i.partnered8 TOTAL_INCOME_T_FAMILY8)) earnings_t_focal8
(pmm, knn(5) include (       earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16          weekly_hrs_t_focal9 i.employed_focal_rec9 housework_focal9 i.educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 i.partnered9 TOTAL_INCOME_T_FAMILY9)) earnings_t_focal9
(pmm, knn(5) include (      earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16           weekly_hrs_t_focal10 i.employed_focal_rec10 housework_focal10 i.educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 i.partnered10 TOTAL_INCOME_T_FAMILY10)) earnings_t_focal10
(pmm, knn(5) include (     earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16            weekly_hrs_t_focal11 i.employed_focal_rec11 housework_focal11 i.educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 i.partnered11 TOTAL_INCOME_T_FAMILY11)) earnings_t_focal11
(pmm, knn(5) include (    earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16             weekly_hrs_t_focal12 i.employed_focal_rec12 housework_focal12 i.educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 i.partnered12 TOTAL_INCOME_T_FAMILY12)) earnings_t_focal12
(pmm, knn(5) include (   earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16              weekly_hrs_t_focal13 i.employed_focal_rec13 housework_focal13 i.educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 i.partnered13 TOTAL_INCOME_T_FAMILY13)) earnings_t_focal13
(pmm, knn(5) include (  earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal15 earnings_t_focal16               weekly_hrs_t_focal14 i.employed_focal_rec14 housework_focal14 i.educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 i.partnered14 TOTAL_INCOME_T_FAMILY14)) earnings_t_focal14
(pmm, knn(5) include ( earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal16                weekly_hrs_t_focal15 i.employed_focal_rec15 housework_focal15 i.educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 i.partnered15 TOTAL_INCOME_T_FAMILY15)) earnings_t_focal15
(pmm, knn(5) include (earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15                 weekly_hrs_t_focal16 i.employed_focal_rec16 housework_focal16 i.educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 i.partnered16 TOTAL_INCOME_T_FAMILY16)) earnings_t_focal16

/* Educational Attainment */
(ologit, include (                i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16 weekly_hrs_t_focal0 i.employed_focal_rec0 housework_focal0 earnings_t_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 i.partnered0 TOTAL_INCOME_T_FAMILY0)) educ_focal0
(ologit, include (               i.educ_focal0 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16  weekly_hrs_t_focal1 i.employed_focal_rec1 housework_focal1 earnings_t_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 i.partnered1 TOTAL_INCOME_T_FAMILY1)) educ_focal1
(ologit, include (              i.educ_focal0 i.educ_focal1 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16   weekly_hrs_t_focal2 i.employed_focal_rec2 housework_focal2 earnings_t_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 i.partnered2 TOTAL_INCOME_T_FAMILY2)) educ_focal2
(ologit, include (             i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16    weekly_hrs_t_focal3 i.employed_focal_rec3 housework_focal3 earnings_t_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 i.partnered3 TOTAL_INCOME_T_FAMILY3)) educ_focal3
(ologit, include (            i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16     weekly_hrs_t_focal4 i.employed_focal_rec4 housework_focal4 earnings_t_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 i.partnered4 TOTAL_INCOME_T_FAMILY4)) educ_focal4
(ologit, include (           i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16      weekly_hrs_t_focal5 i.employed_focal_rec5 housework_focal5 earnings_t_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 i.partnered5 TOTAL_INCOME_T_FAMILY5)) educ_focal5
(ologit, include (          i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16       weekly_hrs_t_focal6 i.employed_focal_rec6 housework_focal6 earnings_t_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 i.partnered6 TOTAL_INCOME_T_FAMILY6)) educ_focal6
(ologit, include (         i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16        weekly_hrs_t_focal7 i.employed_focal_rec7 housework_focal7 earnings_t_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 i.partnered7 TOTAL_INCOME_T_FAMILY7)) educ_focal7
(ologit, include (        i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16         weekly_hrs_t_focal8 i.employed_focal_rec8 housework_focal8 earnings_t_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 i.partnered8 TOTAL_INCOME_T_FAMILY8)) educ_focal8
(ologit, include (       i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16          weekly_hrs_t_focal9 i.employed_focal_rec9 housework_focal9 earnings_t_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 i.partnered9 TOTAL_INCOME_T_FAMILY9)) educ_focal9
(ologit, include (      i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16           weekly_hrs_t_focal10 i.employed_focal_rec10 housework_focal10 earnings_t_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 i.partnered10 TOTAL_INCOME_T_FAMILY10)) educ_focal10
(ologit, include (     i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16            weekly_hrs_t_focal11 i.employed_focal_rec11 housework_focal11 earnings_t_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 i.partnered11 TOTAL_INCOME_T_FAMILY11)) educ_focal11
(ologit, include (    i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal13 i.educ_focal14 i.educ_focal15 i.educ_focal16             weekly_hrs_t_focal12 i.employed_focal_rec12 housework_focal12 earnings_t_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 i.partnered12 TOTAL_INCOME_T_FAMILY12)) educ_focal12
(ologit, include (   i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal14 i.educ_focal15 i.educ_focal16              weekly_hrs_t_focal13 i.employed_focal_rec13 housework_focal13 earnings_t_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 i.partnered13 TOTAL_INCOME_T_FAMILY13)) educ_focal13
(ologit, include (  i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal15 i.educ_focal16               weekly_hrs_t_focal14 i.employed_focal_rec14 housework_focal14 earnings_t_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 i.partnered14 TOTAL_INCOME_T_FAMILY14)) educ_focal14
(ologit, include ( i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal16                weekly_hrs_t_focal15 i.employed_focal_rec15 housework_focal15 earnings_t_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 i.partnered15 TOTAL_INCOME_T_FAMILY15)) educ_focal15
(ologit, include (i.educ_focal0 i.educ_focal1 i.educ_focal2 i.educ_focal3 i.educ_focal4 i.educ_focal5 i.educ_focal6 i.educ_focal7 i.educ_focal8 i.educ_focal9 i.educ_focal10 i.educ_focal11 i.educ_focal12 i.educ_focal13 i.educ_focal14 i.educ_focal15                 weekly_hrs_t_focal16 i.employed_focal_rec16 housework_focal16 earnings_t_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 i.partnered16 TOTAL_INCOME_T_FAMILY16)) educ_focal16

/* Number of Children */
(pmm, knn(5) include (                NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16 weekly_hrs_t_focal0 i.employed_focal_rec0 housework_focal0 i.educ_focal0 earnings_t_focal0 AGE_YOUNG_CHILD_0 i.partnered0 TOTAL_INCOME_T_FAMILY0)) NUM_CHILDREN_0
(pmm, knn(5) include (               NUM_CHILDREN_0 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16  weekly_hrs_t_focal1 i.employed_focal_rec1 housework_focal1 i.educ_focal1 earnings_t_focal1 AGE_YOUNG_CHILD_1 i.partnered1 TOTAL_INCOME_T_FAMILY1)) NUM_CHILDREN_1
(pmm, knn(5) include (              NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16   weekly_hrs_t_focal2 i.employed_focal_rec2 housework_focal2 i.educ_focal2 earnings_t_focal2 AGE_YOUNG_CHILD_2 i.partnered2 TOTAL_INCOME_T_FAMILY2)) NUM_CHILDREN_2
(pmm, knn(5) include (             NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16    weekly_hrs_t_focal3 i.employed_focal_rec3 housework_focal3 i.educ_focal3 earnings_t_focal3 AGE_YOUNG_CHILD_3 i.partnered3 TOTAL_INCOME_T_FAMILY3)) NUM_CHILDREN_3
(pmm, knn(5) include (            NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16     weekly_hrs_t_focal4 i.employed_focal_rec4 housework_focal4 i.educ_focal4 earnings_t_focal4 AGE_YOUNG_CHILD_4 i.partnered4 TOTAL_INCOME_T_FAMILY4)) NUM_CHILDREN_4
(pmm, knn(5) include (           NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16      weekly_hrs_t_focal5 i.employed_focal_rec5 housework_focal5 i.educ_focal5 earnings_t_focal5 AGE_YOUNG_CHILD_5 i.partnered5 TOTAL_INCOME_T_FAMILY5)) NUM_CHILDREN_5
(pmm, knn(5) include (          NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16       weekly_hrs_t_focal6 i.employed_focal_rec6 housework_focal6 i.educ_focal6 earnings_t_focal6 AGE_YOUNG_CHILD_6 i.partnered6 TOTAL_INCOME_T_FAMILY6)) NUM_CHILDREN_6
(pmm, knn(5) include (         NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16        weekly_hrs_t_focal7 i.employed_focal_rec7 housework_focal7 i.educ_focal7 earnings_t_focal7 AGE_YOUNG_CHILD_7 i.partnered7 TOTAL_INCOME_T_FAMILY7)) NUM_CHILDREN_7
(pmm, knn(5) include (        NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16         weekly_hrs_t_focal8 i.employed_focal_rec8 housework_focal8 i.educ_focal8 earnings_t_focal8 AGE_YOUNG_CHILD_8 i.partnered8 TOTAL_INCOME_T_FAMILY8)) NUM_CHILDREN_8
(pmm, knn(5) include (       NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16          weekly_hrs_t_focal9 i.employed_focal_rec9 housework_focal9 i.educ_focal9 earnings_t_focal9 AGE_YOUNG_CHILD_9 i.partnered9 TOTAL_INCOME_T_FAMILY9)) NUM_CHILDREN_9
(pmm, knn(5) include (      NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16           weekly_hrs_t_focal10 i.employed_focal_rec10 housework_focal10 i.educ_focal10 earnings_t_focal10 AGE_YOUNG_CHILD_10 i.partnered10 TOTAL_INCOME_T_FAMILY10)) NUM_CHILDREN_10
(pmm, knn(5) include (     NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16            weekly_hrs_t_focal11 i.employed_focal_rec11 housework_focal11 i.educ_focal11 earnings_t_focal11 AGE_YOUNG_CHILD_11 i.partnered11 TOTAL_INCOME_T_FAMILY11)) NUM_CHILDREN_11
(pmm, knn(5) include (    NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16             weekly_hrs_t_focal12 i.employed_focal_rec12 housework_focal12 i.educ_focal12 earnings_t_focal12 AGE_YOUNG_CHILD_12 i.partnered12 TOTAL_INCOME_T_FAMILY12)) NUM_CHILDREN_12
(pmm, knn(5) include (   NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16              weekly_hrs_t_focal13 i.employed_focal_rec13 housework_focal13 i.educ_focal13 earnings_t_focal13 AGE_YOUNG_CHILD_13 i.partnered13 TOTAL_INCOME_T_FAMILY13)) NUM_CHILDREN_13
(pmm, knn(5) include (  NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_15 NUM_CHILDREN_16               weekly_hrs_t_focal14 i.employed_focal_rec14 housework_focal14 i.educ_focal14 earnings_t_focal14 AGE_YOUNG_CHILD_14 i.partnered14 TOTAL_INCOME_T_FAMILY14)) NUM_CHILDREN_14
(pmm, knn(5) include ( NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_16                weekly_hrs_t_focal15 i.employed_focal_rec15 housework_focal15 i.educ_focal15 earnings_t_focal15 AGE_YOUNG_CHILD_15 i.partnered15 TOTAL_INCOME_T_FAMILY15)) NUM_CHILDREN_15
(pmm, knn(5) include (NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15                 weekly_hrs_t_focal16 i.employed_focal_rec16 housework_focal16 i.educ_focal16 earnings_t_focal16 AGE_YOUNG_CHILD_16 i.partnered16 TOTAL_INCOME_T_FAMILY16)) NUM_CHILDREN_16

/* Age of Youngest Child */
(pmm, knn(5) include (                AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16 weekly_hrs_t_focal0 i.employed_focal_rec0 housework_focal0 i.educ_focal0 earnings_t_focal0 NUM_CHILDREN_0 i.partnered0 TOTAL_INCOME_T_FAMILY0)) AGE_YOUNG_CHILD_0
(pmm, knn(5) include (               AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16  weekly_hrs_t_focal1 i.employed_focal_rec1 housework_focal1 i.educ_focal1 earnings_t_focal1 NUM_CHILDREN_1 i.partnered1 TOTAL_INCOME_T_FAMILY1)) AGE_YOUNG_CHILD_1
(pmm, knn(5) include (              AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16   weekly_hrs_t_focal2 i.employed_focal_rec2 housework_focal2 i.educ_focal2 earnings_t_focal2 NUM_CHILDREN_2 i.partnered2 TOTAL_INCOME_T_FAMILY2)) AGE_YOUNG_CHILD_2
(pmm, knn(5) include (             AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16    weekly_hrs_t_focal3 i.employed_focal_rec3 housework_focal3 i.educ_focal3 earnings_t_focal3 NUM_CHILDREN_3 i.partnered3 TOTAL_INCOME_T_FAMILY3)) AGE_YOUNG_CHILD_3
(pmm, knn(5) include (            AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16     weekly_hrs_t_focal4 i.employed_focal_rec4 housework_focal4 i.educ_focal4 earnings_t_focal4 NUM_CHILDREN_4 i.partnered4 TOTAL_INCOME_T_FAMILY4)) AGE_YOUNG_CHILD_4
(pmm, knn(5) include (           AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16      weekly_hrs_t_focal5 i.employed_focal_rec5 housework_focal5 i.educ_focal5 earnings_t_focal5 NUM_CHILDREN_5 i.partnered5 TOTAL_INCOME_T_FAMILY5)) AGE_YOUNG_CHILD_5
(pmm, knn(5) include (          AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16       weekly_hrs_t_focal6 i.employed_focal_rec6 housework_focal6 i.educ_focal6 earnings_t_focal6 NUM_CHILDREN_6 i.partnered6 TOTAL_INCOME_T_FAMILY6)) AGE_YOUNG_CHILD_6
(pmm, knn(5) include (         AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16        weekly_hrs_t_focal7 i.employed_focal_rec7 housework_focal7 i.educ_focal7 earnings_t_focal7 NUM_CHILDREN_7 i.partnered7 TOTAL_INCOME_T_FAMILY7)) AGE_YOUNG_CHILD_7
(pmm, knn(5) include (        AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16         weekly_hrs_t_focal8 i.employed_focal_rec8 housework_focal8 i.educ_focal8 earnings_t_focal8 NUM_CHILDREN_8 i.partnered8 TOTAL_INCOME_T_FAMILY8)) AGE_YOUNG_CHILD_8
(pmm, knn(5) include (       AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16          weekly_hrs_t_focal9 i.employed_focal_rec9 housework_focal9 i.educ_focal9 earnings_t_focal9 NUM_CHILDREN_9 i.partnered9 TOTAL_INCOME_T_FAMILY9)) AGE_YOUNG_CHILD_9
(pmm, knn(5) include (      AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16           weekly_hrs_t_focal10 i.employed_focal_rec10 housework_focal10 i.educ_focal10 earnings_t_focal10 NUM_CHILDREN_10 i.partnered10 TOTAL_INCOME_T_FAMILY10)) AGE_YOUNG_CHILD_10
(pmm, knn(5) include (     AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16            weekly_hrs_t_focal11 i.employed_focal_rec11 housework_focal11 i.educ_focal11 earnings_t_focal11 NUM_CHILDREN_11 i.partnered11 TOTAL_INCOME_T_FAMILY11)) AGE_YOUNG_CHILD_11
(pmm, knn(5) include (    AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16             weekly_hrs_t_focal12 i.employed_focal_rec12 housework_focal12 i.educ_focal12 earnings_t_focal12 NUM_CHILDREN_12 i.partnered12 TOTAL_INCOME_T_FAMILY12)) AGE_YOUNG_CHILD_12
(pmm, knn(5) include (   AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16              weekly_hrs_t_focal13 i.employed_focal_rec13 housework_focal13 i.educ_focal13 earnings_t_focal13 NUM_CHILDREN_13 i.partnered13 TOTAL_INCOME_T_FAMILY13)) AGE_YOUNG_CHILD_13
(pmm, knn(5) include (  AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16               weekly_hrs_t_focal14 i.employed_focal_rec14 housework_focal14 i.educ_focal14 earnings_t_focal14 NUM_CHILDREN_14 i.partnered14 TOTAL_INCOME_T_FAMILY14)) AGE_YOUNG_CHILD_14
(pmm, knn(5) include ( AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_16                weekly_hrs_t_focal15 i.employed_focal_rec15 housework_focal15 i.educ_focal15 earnings_t_focal15 NUM_CHILDREN_15 i.partnered15 TOTAL_INCOME_T_FAMILY15)) AGE_YOUNG_CHILD_15
(pmm, knn(5) include (AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15                 weekly_hrs_t_focal16 i.employed_focal_rec16 housework_focal16 i.educ_focal16 earnings_t_focal16 NUM_CHILDREN_16 i.partnered16 TOTAL_INCOME_T_FAMILY16)) AGE_YOUNG_CHILD_16

/* Partnership Status */
(logit, include (                i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16 weekly_hrs_t_focal0 i.employed_focal_rec0 housework_focal0 earnings_t_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 i.educ_focal0 TOTAL_INCOME_T_FAMILY0)) partnered0
(logit, include (               i.partnered0 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16  weekly_hrs_t_focal1 i.employed_focal_rec1 housework_focal1 earnings_t_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 i.educ_focal1 TOTAL_INCOME_T_FAMILY1)) partnered1
(logit, include (              i.partnered0 i.partnered1 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16   weekly_hrs_t_focal2 i.employed_focal_rec2 housework_focal2 earnings_t_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 i.educ_focal2 TOTAL_INCOME_T_FAMILY2)) partnered2
(logit, include (             i.partnered0 i.partnered1 i.partnered2 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16    weekly_hrs_t_focal3 i.employed_focal_rec3 housework_focal3 earnings_t_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 i.educ_focal3 TOTAL_INCOME_T_FAMILY3)) partnered3
(logit, include (            i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16     weekly_hrs_t_focal4 i.employed_focal_rec4 housework_focal4 earnings_t_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 i.educ_focal4 TOTAL_INCOME_T_FAMILY4)) partnered4
(logit, include (           i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16      weekly_hrs_t_focal5 i.employed_focal_rec5 housework_focal5 earnings_t_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 i.educ_focal5 TOTAL_INCOME_T_FAMILY5)) partnered5
(logit, include (          i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16       weekly_hrs_t_focal6 i.employed_focal_rec6 housework_focal6 earnings_t_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 i.educ_focal6 TOTAL_INCOME_T_FAMILY6)) partnered6
(logit, include (         i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16        weekly_hrs_t_focal7 i.employed_focal_rec7 housework_focal7 earnings_t_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 i.educ_focal7 TOTAL_INCOME_T_FAMILY7)) partnered7
(logit, include (        i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16         weekly_hrs_t_focal8 i.employed_focal_rec8 housework_focal8 earnings_t_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 i.educ_focal8 TOTAL_INCOME_T_FAMILY8)) partnered8
(logit, include (       i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16          weekly_hrs_t_focal9 i.employed_focal_rec9 housework_focal9 earnings_t_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 i.educ_focal9 TOTAL_INCOME_T_FAMILY9)) partnered9
(logit, include (      i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16           weekly_hrs_t_focal10 i.employed_focal_rec10 housework_focal10 earnings_t_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 i.educ_focal10 TOTAL_INCOME_T_FAMILY10)) partnered10
(logit, include (     i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered12 i.partnered13 i.partnered14 i.partnered15 i.partnered16            weekly_hrs_t_focal11 i.employed_focal_rec11 housework_focal11 earnings_t_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 i.educ_focal11 TOTAL_INCOME_T_FAMILY11)) partnered11
(logit, include (    i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered13 i.partnered14 i.partnered15 i.partnered16             weekly_hrs_t_focal12 i.employed_focal_rec12 housework_focal12 earnings_t_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 i.educ_focal12 TOTAL_INCOME_T_FAMILY12)) partnered12
(logit, include (   i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered14 i.partnered15 i.partnered16              weekly_hrs_t_focal13 i.employed_focal_rec13 housework_focal13 earnings_t_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 i.educ_focal13 TOTAL_INCOME_T_FAMILY13)) partnered13
(logit, include (  i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered15 i.partnered16               weekly_hrs_t_focal14 i.employed_focal_rec14 housework_focal14 earnings_t_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 i.educ_focal14 TOTAL_INCOME_T_FAMILY14)) partnered14
(logit, include ( i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered16                weekly_hrs_t_focal15 i.employed_focal_rec15 housework_focal15 earnings_t_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 i.educ_focal15 TOTAL_INCOME_T_FAMILY15)) partnered15
(logit, include (i.partnered0 i.partnered1 i.partnered2 i.partnered3 i.partnered4 i.partnered5 i.partnered6 i.partnered7 i.partnered8 i.partnered9 i.partnered10 i.partnered11 i.partnered12 i.partnered13 i.partnered14 i.partnered15                 weekly_hrs_t_focal16 i.employed_focal_rec16 housework_focal16 earnings_t_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 i.educ_focal16 TOTAL_INCOME_T_FAMILY16)) partnered16

/* Family Income */
(pmm, knn(5) include (                TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16 weekly_hrs_t_focal0 i.employed_focal_rec0 housework_focal0 i.educ_focal0 earnings_t_focal0 NUM_CHILDREN_0 i.partnered0 AGE_YOUNG_CHILD_0)) TOTAL_INCOME_T_FAMILY0
(pmm, knn(5) include (               TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16  weekly_hrs_t_focal1 i.employed_focal_rec1 housework_focal1 i.educ_focal1 earnings_t_focal1 NUM_CHILDREN_1 i.partnered1 AGE_YOUNG_CHILD_1)) TOTAL_INCOME_T_FAMILY1
(pmm, knn(5) include (              TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16   weekly_hrs_t_focal2 i.employed_focal_rec2 housework_focal2 i.educ_focal2 earnings_t_focal2 NUM_CHILDREN_2 i.partnered2 AGE_YOUNG_CHILD_2)) TOTAL_INCOME_T_FAMILY2
(pmm, knn(5) include (             TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16    weekly_hrs_t_focal3 i.employed_focal_rec3 housework_focal3 i.educ_focal3 earnings_t_focal3 NUM_CHILDREN_3 i.partnered3 AGE_YOUNG_CHILD_3)) TOTAL_INCOME_T_FAMILY3
(pmm, knn(5) include (            TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16     weekly_hrs_t_focal4 i.employed_focal_rec4 housework_focal4 i.educ_focal4 earnings_t_focal4 NUM_CHILDREN_4 i.partnered4 AGE_YOUNG_CHILD_4)) TOTAL_INCOME_T_FAMILY4
(pmm, knn(5) include (           TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16      weekly_hrs_t_focal5 i.employed_focal_rec5 housework_focal5 i.educ_focal5 earnings_t_focal5 NUM_CHILDREN_5 i.partnered5 AGE_YOUNG_CHILD_5)) TOTAL_INCOME_T_FAMILY5
(pmm, knn(5) include (          TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16       weekly_hrs_t_focal6 i.employed_focal_rec6 housework_focal6 i.educ_focal6 earnings_t_focal6 NUM_CHILDREN_6 i.partnered6 AGE_YOUNG_CHILD_6)) TOTAL_INCOME_T_FAMILY6
(pmm, knn(5) include (         TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16        weekly_hrs_t_focal7 i.employed_focal_rec7 housework_focal7 i.educ_focal7 earnings_t_focal7 NUM_CHILDREN_7 i.partnered7 AGE_YOUNG_CHILD_7)) TOTAL_INCOME_T_FAMILY7
(pmm, knn(5) include (        TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16         weekly_hrs_t_focal8 i.employed_focal_rec8 housework_focal8 i.educ_focal8 earnings_t_focal8 NUM_CHILDREN_8 i.partnered8 AGE_YOUNG_CHILD_8)) TOTAL_INCOME_T_FAMILY8
(pmm, knn(5) include (       TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16          weekly_hrs_t_focal9 i.employed_focal_rec9 housework_focal9 i.educ_focal9 earnings_t_focal9 NUM_CHILDREN_9 i.partnered9 AGE_YOUNG_CHILD_9)) TOTAL_INCOME_T_FAMILY9
(pmm, knn(5) include (      TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16           weekly_hrs_t_focal10 i.employed_focal_rec10 housework_focal10 i.educ_focal10 earnings_t_focal10 NUM_CHILDREN_10 i.partnered10 AGE_YOUNG_CHILD_10)) TOTAL_INCOME_T_FAMILY10
(pmm, knn(5) include (     TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16            weekly_hrs_t_focal11 i.employed_focal_rec11 housework_focal11 i.educ_focal11 earnings_t_focal11 NUM_CHILDREN_11 i.partnered11 AGE_YOUNG_CHILD_11)) TOTAL_INCOME_T_FAMILY11
(pmm, knn(5) include (    TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16             weekly_hrs_t_focal12 i.employed_focal_rec12 housework_focal12 i.educ_focal12 earnings_t_focal12 NUM_CHILDREN_12 i.partnered12 AGE_YOUNG_CHILD_12)) TOTAL_INCOME_T_FAMILY12
(pmm, knn(5) include (   TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16              weekly_hrs_t_focal13 i.employed_focal_rec13 housework_focal13 i.educ_focal13 earnings_t_focal13 NUM_CHILDREN_13 i.partnered13 AGE_YOUNG_CHILD_13)) TOTAL_INCOME_T_FAMILY13
(pmm, knn(5) include (  TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16               weekly_hrs_t_focal14 i.employed_focal_rec14 housework_focal14 i.educ_focal14 earnings_t_focal14 NUM_CHILDREN_14 i.partnered14 AGE_YOUNG_CHILD_14)) TOTAL_INCOME_T_FAMILY14
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY16                weekly_hrs_t_focal15 i.employed_focal_rec15 housework_focal15 i.educ_focal15 earnings_t_focal15 NUM_CHILDREN_15 i.partnered15 AGE_YOUNG_CHILD_15)) TOTAL_INCOME_T_FAMILY15
(pmm, knn(5) include (TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15                 weekly_hrs_t_focal16 i.employed_focal_rec16 housework_focal16 i.educ_focal16 earnings_t_focal16 NUM_CHILDREN_16 i.partnered16 AGE_YOUNG_CHILD_16)) TOTAL_INCOME_T_FAMILY16

= birth_yr_all i.raceth_fixed_focal i.sample_type, by(SEX) chaindots add(1) rseed(12345) noimputed augment force // dryrun // noisily i.rel_start_all  FIRST_BIRTH_YR

;
#delimit cr

// = i.FIRST_BIRTH_YR i.birth_yr_all i.rel_start_all i.raceth_fixed_focal i.sample_type i.SEX, chaindots add(1) rseed(12345) noimputed augment noisily force // dryrun

**# saved files and descriptive distributions

save "$created_data/psid_individs_imputed_wide_cond", replace // okay, now that this worked with more variables, will replace above version

// reshape back to long to look at descriptives
mi reshape long in_sample_ relationship_  partnered weekly_hrs_t1_focal earnings_t1_focal housework_focal employed_focal educ_focal college_focal age_focal weekly_hrs_t2_focal earnings_t2_focal employed_t2_focal start_yr_employer_focal yrs_employer_focal children FAMILY_INTERVIEW_NUM_ NUM_CHILDREN_ AGE_YOUNG_CHILD_ TOTAL_INCOME_T1_FAMILY_ hours_type_t1_focal hw_hours_gp raceth_focal weekly_hrs_t_focal earnings_t_focal TOTAL_INCOME_T_FAMILY childcare_focal adultcare_focal TOTAL_INCOME_T2_FAMILY_ employed_focal_rec has_hours_t1 has_earnings_t1 has_hours_t2 has_earnings_t2 employed_t1_hrs_focal employed_t1_earn_focal ///
, i(couple_id unique_id partner_id rel_start_all min_dur max_dur rel_end_yr last_yr_observed ended SEX) j(duration_rec)

mi convert flong

browse couple_id unique_id partner_id duration_rec weekly_hrs_t_focal employed_focal employed_focal_rec housework_focal _mi_miss _mi_m _mi_id

gen imputed=0
replace imputed=1 if inrange(_mi_m,1,10)

inspect weekly_hrs_t_focal if imputed==0
inspect weekly_hrs_t_focal if imputed==1

tab weekly_hrs_t_focal employed_focal, m
tab weekly_hrs_t_focal employed_focal_rec, m
tab weekly_hrs_t_focal employed_focal if imputed==1, m
tab weekly_hrs_t_focal employed_focal_rec if imputed==1, m // well ,this will actually add MORE 0s, right? because now it is imputing hours for people when employment==0, because it doesn't know.

inspect housework_focal if imputed==0
inspect housework_focal if imputed==1

// mi register regular n

save "$created_data/psid_individs_imputed_long_cond", replace

tabstat weekly_hrs_t_focal housework_focal, by(imputed) stats(mean sd p50)
tabstat weekly_hrs_t_focal housework_focal if SEX==1, by(imputed) stats(mean sd p50)
tabstat weekly_hrs_t_focal housework_focal if SEX==2, by(imputed) stats(mean sd p50)

twoway (histogram weekly_hrs_t_focal if imputed==0, width(2) color(blue%30)) (histogram weekly_hrs_t_focal if imputed==1, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Employment Hours")
twoway (histogram housework_focal if imputed==0, width(2) color(blue%30)) (histogram housework_focal if imputed==1, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Housework Hours")

preserve

collapse (mean) weekly_hrs_t_focal housework_focal, by(duration_rec imputed)

twoway (line weekly_hrs_t_focal duration_rec if imputed==0) (line weekly_hrs_t_focal duration_rec if imputed==1), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) ytitle("Weekly Employment Hours") title("Avg Employment Hours by Duration") xtitle("Marital Duration")
twoway (line housework_focal duration_rec if imputed==0) (line housework_focal duration_rec if imputed==1), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) ytitle("Weekly Housework Hours") title("Avg Housework Hours by Duration") xtitle("Marital Duration")

restore


