********************************************************************************
*** PSID-SHELF DATA PROJECT                                           **********
*** Construction - 01 Collect ethnoracial variables                   **********
*** Last update: 2023.10.09, DD                                       **********
********************************************************************************
          
*-------------------------------------------------------------------------*
* File preamble
*-------------------------------------------------------------------------*

/*
* This file is used to construct the PSID's Social, Health, and Economic 
* Longitudinal File (PSID-SHELF). The "01 Collect ethnoracial variables" file 
* identifies ethnoracial characteristics, related to: reported race; and 
* reported ethnic origin.

* The following variables are generated by this file:

        * REPORTED RACE
        * (1)  race1mreprp      RP's reported race, mention 1
        * (2)  race2mreprp      RP's reported race, mention 2
        * (3)  race3mreprp      RP's reported race, mention 3
        * (4)  race4mreprp      RP's reported race, mention 4
        * (5)  race1mrepsp      SP's reported race, mention 1
        * (6)  race2mrepsp      SP's reported race, mention 2
        * (7)  race3mrepsp      SP's reported race, mention 3
        * (8)  race4mrepsp      SP's reported race, mention 4
        
        * REPORTED ETHNIC ORIGIN
        * (9)  ethospanreprp    RP's reported ethnic origin, Spanish descent
        * (10) ethospanrepsp    SP's reported ethnic origin, Spanish descent

* This file uses the PSID Complete Main Study, 1968–2019. 
*/


*-------------------------------------------------------------------------*
* Data attribution
*-------------------------------------------------------------------------*

/*
* PSID-SHELF started as a project led by Fabian Pfeffer. The data and 
* construction files were compiled by Davis Daumler. 

* Analytic contributions were provided by Patricia Andreski, Davis Daumler, 
* Esther Friedman, Florian Hertel, Noura Insolera, Fabian Pfeffer, Mehmet 
* Zahid Samancioglu, Andreja Siliunas, and Brittany Vasquez.
*/


*-------------------------------------------------------------------------*
* Open the PSID Complete Main Study, 1968–2019
*-------------------------------------------------------------------------*

* Prepare for large dataset:
clear 
clear matrix
clear mata
set maxvar 120000

* Open the PSID Complete Main Study:
use "${data_psid_cms_root}/PSID_COMPLETE_MAIN_STUDY_1968_2019.dta", clear


*-------------------------------------------------------------------------*
* Data preparation
*-------------------------------------------------------------------------*

* Set macro for every survey year of the PSID: 1968/1997, 1999(2)2019
* (I.e., to accommodate the PSID's annual/biennial data structure.)
numlist "1968/1997 1999(2)2019"
global year = r(numlist)
global n_year = wordcount("$year")
di "N years = ${n_year}; years: ${year}."


*-------------------------------------------------------------------------*
* Value labels
*-------------------------------------------------------------------------*

/*
* Note: There are considerable differences in how racial identities were coded
* across survey years. This led to the need for duplicate value labels: 

    (PSID-SHELF value label) 04 "Asian"
    (PSID-SHELF value label) 05 "Native Hawaiian or Pacific Islander"
    (PSID-SHELF value label) 06 "Asian or Pacific Islander"

* The chief goal of the harmonized measures is to maximize detail for users and 
* to eliminate variable inconsistencies across years.

* From 1968 to 1984, it was impossible to distinguish Asians from Pacific 
* Islanders. Beginning in 1985, the combined category was separated into two
* categories. Similarly, (PSID-SHELF value label) 03 "American Indian or Alaska
* Native" was only introduced as a category in 1985. From 1968–2003, there were
* different iterations of (PSID-SHELF value label) 08 "Mentions Spanish origin
* or descent", which continued, even after the PSID introduced a question about
* ethnic origin/Spanish descent in 1985; some individuals continued to have
* racial identities coded as "Hispanic" or "Spanish origin or descent". Prior to
* 1994, individuals could also be coded as (PSID-SHELF value label) 09 "More
* than one mention", even after the PSID introduced second reports for
* racial identity in in 1985, though this category ceased after the PSID 
* introduced third and fourth reports of racial identity in 1994. 
*/

* Race:
#delimit ;
lab def race_9cat
    1 "White"
    2 "Black"
    3 "American Indian or Alaska Native"
    4 "Asian"
    5 "Native Hawaiian or Pacific Islander"
    6 "Asian or Pacific Islander"
    7 "Other race"
    8 "Mentions Spanish origin or descent"
    9 "More than one mention"
    , modify
;
#delimit cr

* Ethnic origin, Spanish descent:
#delimit ;
lab def ethospanrep_8cat
    0 "No Spanish descent"
    1 "Spanish descent (Mexican)"
    2 "Spanish descent (Mexican American)"
    3 "Spanish descent (Chicano)"
    4 "Spanish descent (Puerto Rican)"
    5 "Spanish descent (Cuban)"
    6 "Spanish descent (Hispanic, Latino, other ethnicity of Spanish descent)"
    7 "Spanish descent (More than one mention)"
    , modify
;
#delimit cr

* Describe the newly created value labels:
#delimit ;
lab list 
    race_9cat
    ethospanrep_8cat
;
#delimit cr


*-------------------------------------------------------------------------*
* (1) race1mreprp - RP's reported race, mention 1
*-------------------------------------------------------------------------*

/*
* Note: Between 1968 and 1972, racial identities were collected by interviewer
* observation; i.e., there were no specific questions in the interview asking
* respondents to report their own racial identity. Between 1973 and 1984, there
* was no new information about racial identity (incl. interviewer observation)
* because, as the codebook specifies, "most interviews were taken by telephone".
* As a result, racial identities between 1973 and 1984 were carried forward from
* the 1972 interview and splitoff households were assumed to be the "same race"
* as the main family (from which they split off). In 1985, questions about
* racial identity were introduced to the interview. Finally, between 1994 and
* 1996, and again between 1999 and 2001, reports of race were carried forward
* for the reference person and spouse/partner unless they were newly added to 
* the sample (e.g., a reference person moves in with a new spouse/partner who
* has never been observed in the reference couple of a PSID family unit). It was
* not until 2003 that questions about race were asked biennially of every 
* reference person and spouse/partner.
*/

* Collect the variables that correspond to each survey year:
global var_race1mreprp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  V181        V801        /*
       197X */  V1490       V2202       V2828       V3300       V3720       V4204       V5096       V5662       V6209       V6802       /*
       198X */  V7447       V8099       V8723       V9408       V11055      V11938      V13565      V14612      V16086      V17483      /*
       199X */  V18814      V20114      V21420      V23276      ER3944      ER6814      ER9060      ER11848                 ER15928     /*
       200X */              ER19989                 ER23426                 ER27393                 ER40565                 ER46543     /*
       201X */              ER51904                 ER57659                 ER64810                 ER70882                 ER76897     

* Loop through the original variables that are available in each survey year:
capture noisily drop race1mreprp*
foreach i of numlist 1/$n_year {
	local y:   word `i' of ${year}
	local var: word `i' of ${var_race1mreprp}
    
    * Generate a new variable for the SHELF data:
    gen race1mreprp`y'=-1  /* (Note: All value labels should be assigned; therefore, if any variable includes a minimum value of -1, it means that one or more value labels were not assigned.) */
	lab var race1mreprp`y' "RP's reported race, mention 1, `y' [`var']"
    
    * 1968-1984 coding scheme:
    replace race1mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1968, 1984)
    replace race1mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1968, 1984)
    replace race1mreprp`y'=8 if inlist(`var', 3)                    & inrange(`y', 1968, 1984)
    replace race1mreprp`y'=7 if inlist(`var', 7)                    & inrange(`y', 1968, 1984)
    replace race1mreprp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1968, 1984)
    replace race1mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 1968, 1984)
    
    * 1985-1993 coding scheme:
    replace race1mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1985, 1993)
    replace race1mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 1985, 1993)
    
    * 1994-2003 coding scheme:
    replace race1mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race1mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race1mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race1mreprp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race1mreprp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race1mreprp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race1mreprp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race1mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race1mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race1mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race1mreprp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race1mreprp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race1mreprp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race1mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/$n_year {
	local y:   word `i' of ${year}
    
    * Assign value labels to the newly created variable:
    lab val race1mreprp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race1mreprp*


*-------------------------------------------------------------------------*
* (2) race2mreprp - RP's reported race, mention 2
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_race2mreprp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           V11939      V13566      V14613      V16087      V17484      /*
       199X */  V18815      V20115      V21421      V23277      ER3945      ER6815      ER9061      ER11849                 ER15929     /*
       200X */              ER19990                 ER23427                 ER27394                 ER40566                 ER46544     /*
       201X */              ER51905                 ER57660                 ER64811                 ER70883                 ER76898     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1984" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race2mreprp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race2mreprp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
    gen race2mreprp`y'=-1  /* (Note: All value labels should be assigned; therefore, if any variable includes a minimum value of -1, it means that one or more value labels were not assigned.) */
	lab var race2mreprp`y' "RP's reported race, mention 2, `y' [`var']"
    
    * 1985-1993 coding scheme:
    replace race2mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1985, 1993)
    replace race2mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 1985, 1993)
    
    * 1994-2003 coding scheme:
    replace race2mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race2mreprp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race2mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race2mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race2mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race2mreprp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race2mreprp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race2mreprp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race2mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race2mreprp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race2mreprp*


*-------------------------------------------------------------------------*
* (3) race3mreprp - RP's reported race, mention 3
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_race3mreprp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           .           .           .           .           .           /*
       199X */  .           .           .           .           ER3946      ER6816      ER9062      ER11850                 ER15930     /*
       200X */              ER19991                 ER23428                 ER27395                 ER40567                 ER46545     /*
       201X */              ER51906                 ER57661                 ER64812                 ER70884                 ER76899     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1993" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race3mreprp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race3mreprp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
    gen race3mreprp`y'=-1  /* (Note: All value labels should be assigned; therefore, if any variable includes a minimum value of -1, it means that one or more value labels were not assigned.) */
	lab var race3mreprp`y' "RP's reported race, mention 3, `y' [`var']"
    
    * 1994-2003 coding scheme:
    replace race3mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race3mreprp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race3mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race3mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race3mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race3mreprp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race3mreprp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race3mreprp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race3mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race3mreprp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race3mreprp*


*-------------------------------------------------------------------------*
* (4) race4mreprp - RP's reported race, mention 4
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_race4mreprp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           .           .           .           .           .           /*
       199X */  .           .           .           .           .           .           .           ER11851                 ER15931     /*
       200X */              ER19992                 ER23429                 ER27396                 ER40568                 ER46546     /*
       201X */              ER51907                 ER57662                 ER64813                 ER70885                 ER76900     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1996" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race4mreprp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race4mreprp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen race4mreprp`y'=(`var')
	lab var race4mreprp`y' "RP's reported race, mention 4, `y' [`var']"
    
    * 1994-2003 coding scheme:
    replace race4mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race4mreprp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race4mreprp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race4mreprp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race4mreprp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race4mreprp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race4mreprp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race4mreprp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race4mreprp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race4mreprp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race4mreprp*


*-------------------------------------------------------------------------*
* (5) race1mrepsp - SP's reported race, mention 1
*-------------------------------------------------------------------------*

/*
* Note: In 1985, questions about racial identity were introduced to the 
* interview. Finally, between 1994 and 1996, and again between 1999 and 2001, 
* reports of race were carried forward for the reference person and 
* spouse/partner unless they were newly added to the sample (e.g., a reference 
* person moves in with a new spouse/partner who has never been observed in the 
* reference couple of a PSID family unit). It was not until 2003 that questions 
* about race were asked biennially of every reference person and spouse/partner.
*/

* Collect the variables that correspond to each survey year:
global var_race1mrepsp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           V12293      V13500      V14547      V16021      V17418      /*
       199X */  V18749      V20049      V21355      V23212      ER3883      ER6753      ER8999      ER11760                 ER15836     /*
       200X */              ER19897                 ER23334                 ER27297                 ER40472                 ER46449     /*
       201X */              ER51810                 ER57549                 ER64671                 ER70744                 ER76752     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1984" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race1mrepsp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race1mrepsp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen race1mrepsp`y'=(`var')
	lab var race1mrepsp`y' "SP's reported race, mention 1, `y' [`var']"
    
    * 1985-1993 coding scheme:
    replace race1mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1985, 1993)
    replace race1mrepsp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 1985, 1993)
    
    * 1994-2003 coding scheme:
    replace race1mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race1mrepsp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race1mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race1mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race1mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race1mrepsp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race1mrepsp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race1mrepsp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race1mrepsp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race1mrepsp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race1mrepsp*


*-------------------------------------------------------------------------*
* (6) race2mrepsp - SP's reported race, mention 2
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_race2mrepsp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           V12294      V13501      V14548      V16022      V17419      /*
       199X */  V18750      V20050      V21356      V23213      ER3884      ER6754      ER9000      ER11761                 ER15837     /*
       200X */              ER19898                 ER23335                 ER27298                 ER40473                 ER46450     /*
       201X */              ER51811                 ER57550                 ER64672                 ER70745                 ER76753     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1984" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race2mrepsp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race2mrepsp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen race2mrepsp`y'=(`var')
	lab var race2mrepsp`y' "SP's reported race, mention 2, `y' [`var']"
    
    * 1985-1993 coding scheme:
    replace race2mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1985, 1993)
    replace race2mrepsp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 1985, 1993)
    
    * 1994-2003 coding scheme:
    replace race2mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race2mrepsp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race2mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race2mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race2mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race2mrepsp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race2mrepsp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race2mrepsp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race2mrepsp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race2mrepsp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race2mrepsp*


*-------------------------------------------------------------------------*
* (7) race3mrepsp - SP's reported race, mention 3
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_race3mrepsp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           .           .           .           .           .           /*
       199X */  .           .           .           .           ER3885      ER6755      ER9001      ER11762                 ER15838     /*
       200X */              ER19899                 ER23336                 ER27299                 ER40474                 ER46451     /*
       201X */              ER51812                 ER57551                 ER64673                 ER70746                 ER76754     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1993" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race3mrepsp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race3mrepsp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen race3mrepsp`y'=(`var')
	lab var race3mrepsp`y' "SP's reported race, mention 3, `y' [`var']"
    
    * 1994-2003 coding scheme:
    replace race3mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race3mrepsp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race3mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race3mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race3mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race3mrepsp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race3mrepsp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race3mrepsp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race3mrepsp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race3mrepsp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race3mrepsp*


*-------------------------------------------------------------------------*
* (8) race4mrepsp - SP's reported race, mention 4
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_race4mrepsp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           .           .           .           .           .           /*
       199X */  .           .           .           .           .           .           .           ER11763                 ER15839     /*
       200X */              ER19900                 ER23337                 ER27300                 ER40475                 ER46452     /*
       201X */              ER51813                 ER57552                 ER64674                 ER70747                 ER76755     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1996" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_race4mrepsp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop race4mrepsp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen race4mrepsp`y'=(`var')
	lab var race4mrepsp`y' "SP's reported race, mention 4, `y' [`var']"
    
    * 1994-2003 coding scheme:
    replace race4mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=6 if inlist(`var', 4)                    & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=8 if inlist(`var', 5)                    & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=7 if inlist(`var', 6, 7)                 & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=9 if inlist(`var', 8)                    & inrange(`y', 1994, 2003)
    replace race4mrepsp`y'=. if inlist(`var', 0, 8, 9) | (`var'==.) & inrange(`y', 1994, 2003)
    
    * 2005-present coding scheme:
    replace race4mrepsp`y'=1 if inlist(`var', 1)                    & inrange(`y', 2005, 2099)
    replace race4mrepsp`y'=2 if inlist(`var', 2)                    & inrange(`y', 2005, 2099)
    replace race4mrepsp`y'=3 if inlist(`var', 3)                    & inrange(`y', 2005, 2099)
    replace race4mrepsp`y'=4 if inlist(`var', 4)                    & inrange(`y', 2005, 2099)
    replace race4mrepsp`y'=5 if inlist(`var', 5)                    & inrange(`y', 2005, 2099)
    replace race4mrepsp`y'=7 if inlist(`var', 7)                    & inrange(`y', 2005, 2099)
    replace race4mrepsp`y'=. if inlist(`var', 0, 9) | (`var'==.)    & inrange(`y', 2005, 2099)
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val race4mrepsp`y' race_9cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize race4mrepsp*


*-------------------------------------------------------------------------*
* (9) ethospanreprp - RP's reported ethnic origin, Spanish descent
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_ethospanreprp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           V11937      V13564      V14611      V16085      V17482      /*
       199X */  V18813      V20113      V21419      V23275      ER3941      ER6811      ER9057      .                       .           /*
       200X */              .                       .                       ER27392                 ER40564                 ER46542     /*
       201X */              ER51903                 ER57658                 ER64809                 ER70881                 ER76896     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1984 1997 1999(2)2003" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_ethospanreprp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop ethospanreprp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen ethospanreprp`y'=-1  /* (Note: All value labels should be assigned; therefore, if any variable includes a minimum value of -1, it means that one or more value labels were not assigned.) */
	replace ethospanreprp`y'=(`var') if inrange(`var', 1, 5)
	replace ethospanreprp`y'=7       if inlist(`var',  6)
	replace ethospanreprp`y'=6       if inlist(`var',  7)
	replace ethospanreprp`y'=.       if inlist(`var',  0, 9) | (`var'==.)
	lab var ethospanreprp`y' "RP's reported ethnic origin, Spanish descent, `y' [`var']"
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val ethospanreprp`y' ethospanrep_8cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize ethospanreprp*


*-------------------------------------------------------------------------*
* (10) ethospanrepsp - SP's reported ethnic origin, Spanish descent
*-------------------------------------------------------------------------*

* Collect the variables that correspond to each survey year:
global var_ethospanrepsp /*
                0           1           2           3           4           5           6           7           8           9             
       196X */                                                                                                  .           .           /*
       197X */  .           .           .           .           .           .           .           .           .           .           /*
       198X */  .           .           .           .           .           V12292      V13499      V14546      V16020      V17417      /*
       199X */  V18748      V20048      V21354      V23211      ER3880      ER6750      ER8996      .                       .           /*
       200X */              .                       .                       ER27296                 ER40471                 ER46448     /*
       201X */              ER51809                 ER57548                 ER64670                 ER70743                 ER76751     

* Prepare to loop through a subset of survey years, by setting three required
* inputs to run the program that generates a subset of PSID survey years:
local set_psid_yr_all    "${year}"
local set_psid_yr_miss   "1968/1984 1997 1999(2)2003" /* (Note: Specify the survey years in which the variable is missing; do not include years in which the survey was not conducted: i.e., 1998(2)2018.) */
local set_psid_var_avail "${var_ethospanrepsp}"

* Run the program that generates the a subset of PSID survey years:
rsubsetpsid /* [Input 1] */ "`set_psid_yr_all'" /* [Input 2] */  "`set_psid_yr_miss'" /* [Input 3] */  "`set_psid_var_avail'"

* Loop through the original variables that are available in each survey year, 
* using the program's resulting local macros:
capture noisily drop ethospanrepsp*
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
	local var: word `i' of `=r(var_avail)'
  
    * Generate a new variable for the SHELF data:
	gen ethospanrepsp`y'=-1  /* (Note: All value labels should be assigned; therefore, if any variable includes a minimum value of -1, it means that one or more value labels were not assigned.) */
	replace ethospanrepsp`y'=(`var') if inrange(`var', 1, 5)
	replace ethospanrepsp`y'=7       if inlist(`var',  6)
	replace ethospanrepsp`y'=6       if inlist(`var',  7)
	replace ethospanrepsp`y'=.       if inlist(`var',  0, 9) | (`var'==.)
	lab var ethospanrepsp`y' "SP's reported ethnic origin, Spanish descent, `y' [`var']"
}

* Loop through the new variables that are available in each survey year:
foreach i of numlist 1/`=r(n_year_avail)' {
	local y:   word `i' of `=r(year_avail)'
    
    * Assign value labels to the newly created variable:
    lab val ethospanrepsp`y' ethospanrep_8cat
}

/*
* Note: There are marked disjunctures in how race/ethnicity was measured by the 
* PSID, with respect to: (1) when multiple reports of racial identity were 
* permitted (1985: second mentions; 1994: third and fourth mentions); crucially, 
* (2) when ethnic origin was systematically collected for Hispanic-identifying 
* individuals who were members of the reference couple (1985); and, finally, 
* (3) regarding how racial identity was collected across waves, changing from 
* interviewer identification, with no input from the respondent (1968-1972), to 
* no new reports of race due to the shift to telephone interviews (1973–1984), 
* and then questions about race/ethnicity being added to the survey interview,
* such that respondents self-identify their race/ethnicity (1985–present). 
*/

* Describe the newly created variables:
summarize ethospanrepsp*


*-------------------------------------------------------------------------*
* Prepare to save ethnoracial variables
*-------------------------------------------------------------------------*

* Identify ethnoracial variables:
#delimit ;
global var_collect_ethnoracial
       race1mreprp*
       race2mreprp*
       race3mreprp*
       race4mreprp*
       race1mrepsp*
       race2mrepsp*
       race3mrepsp*
       race4mrepsp*
       ethospanreprp*
       ethospanrepsp*
;
global n_var_collect_ethnoracial = wordcount("${var_collect_ethnoracial}")
;
#delimit cr

* Check variable count:
di "N (sets of) vars total = ${n_var_collect_ethnoracial}"


*-------------------------------------------------------------------------*
* Save the ethnoracial variables in wide format
*-------------------------------------------------------------------------*

* Rename unique ID to lowercase:
rename ID, lower

* Keep and reorder variables:
keep id ${var_collect_ethnoracial}
order id ${var_collect_ethnoracial}

* Sort data:
sort id

* Describe data:
describe, short
codebook id

* Compress file size:
compress

* Save the ethnoracial variables in wide format:
save "${psidshelf_root}/Construction_Files/Data/Merge/datagen_shelf_01_ethnoracial_wide.dta", replace
